export const api = {
    // MAIN_URL: '',
    // MAIN_URL: 'https://samimgroup.local',
    // MAIN_URL: 'https://10.1.24.179',
    MAIN_URL: 'https://www.samimgroup.com',
    DATA_BASE_NAME: 'samim',
    API_GET_SESSION: '/api/session',
    API_GET_PROFILE_INFORMATION: '/api/profile',
    API_HOME_POSTS: '/api/blog/',
    API_CONTENT_POST: '/api/blog/post',
    API_PRODUCTS: '/api/shop/',
    API_INFORMATION_PRODUCT: '/api/shop/product/',
    API_LIST_CATEGORIES: '/api/categories/',
    API_ALL_TAGS: '/api/blog/allTag',
    API_LOGIN: '/api/web/login',
    API_TWO_AUTH: '/api/web/get_two_authentication',
    API_LOGOUT: '/api/web/logout',
    API_CONTACT_US: '/api/web/website_contact_us/crm.lead',
    API_SEARCH: '/api/v1/search',
    API_AUTH: '/api/web/auth',
    API_SEND_SMS: '/api/web/send/code',
    API_VERIFICATION: '/api/web/verification',
    API_POST_AVAILABLE: '/api/blog/available/post',
    URL_IMAGE_BLOG_FIRST_SECTION: '/web/image/blog.post/',
    URL_IMAGE_PRODUCT: '/web/image/product.image/',
    URL_IMAGE_BLOG_SECOND_SECTION: '/post_image',
    URL_IMAGE_SINGLE_BLOG_SECOND_SECTION: '/post_image',
    URL_IMAGE_PRODUCT_FIRST_SECTION: '/web/image/product.template/',
    URL_IMAGE_PRODUCT_SECOND_SECTION: '/image',
    IMAGE_SIZE_POSTS_IN_HOME: '/387x191',
}
