export const valueLabels = {
    LABEL_LINK_FOOTER_BLOG_EN: "blog",
    LABEL_LINK_FOOTER_ABOUT_US_FA: "درباره ما",
    LABEL_LINK_FOOTER_RESOURCES_FA: "منابع",
    LABEL_LINK_FOOTER_ABOUT_US_FA_SAMIM: "صمیم در یک نگاه",
    LABEL_LINK_FOOTER_ABOUT_US_PERMISSIONS: "مجوزها",
    LABEL_LINK_FOOTER_ABOUT_US_CUSTOMERS: "مشتریان",
    LABEL_LINK_FOOTER_ABOUT_US_ACHIEVEMENTS: "افتخارات",
    LABEL_LINK_FOOTER_PRODUCTS_FA: "محصولات",
    LABEL_LINK_FOOTER_SOLUTIONS_FA: "راهکارها ",
    LABEL_LINK_FOOTER_SOLUTIONS_1: "سامانه یکپارچه مدیریت محتوا ",
    LABEL_LINK_FOOTER_SOLUTIONS_2: "سامانه جامع نرم افزاری کنترل و مانیتورینگ",
    LABEL_LINK_FOOTER_SOLUTIONS_3: "گذار از SDI به IP",
    LABEL_LINK_FOOTER_SOLUTIONS_4: "سامانه ارسال محتوای زنده ",
    LABEL_LINK_FOOTER_SOLUTIONS_5: "تلویزیون‌های تعاملی OTT/VOD",
    LABEL_LINK_FOOTER_SUPPORT_FA: "پشتیبانی",
    LABEL_LINK_FOOTER_CAREERS_FA: "فرصت های شغلی",
    LABEL_LINK_FOOTER_BLOG_FA: "بلاگ",
    LABEL_LINK_FOOTER_CONTACT_US_FA: "تماس با ما",
    LABEL_TITLE_FOOTER_FIRST_EN: "Modular Products",
    LABEL_TITLE_FOOTER_SECOND_EN: "Routers and Control Panels",
    LABEL_TITLE_FOOTER_THREE_EN: "Multiviewers",
    LABEL_TITLE_FOOTER_FOURTH_EN: "IP Intercom",
    LABEL_TITLE_LINK_FOOTER_FIRST_1_EN: "فریم هاو تجهیزات جانبی",
    LABEL_TITLE_LINK_FOOTER_FIRST_2_EN: "مبدل صداوتصویر",
    LABEL_TITLE_LINK_FOOTER_FIRST_3_EN: "مبدل فیبر",
    LABEL_TITLE_LINK_FOOTER_FIRST_4_EN: "توزیع کننده صداوتصویر",
    LABEL_TITLE_LINK_FOOTER_FIRST_5_EN: "پردازنده صداو تصویر",
    LABEL_TITLE_LINK_FOOTER_FIRST_6_EN: "مالتی ویوئر",
    LABEL_TITLE_LINK_FOOTER_FIRST_7_EN: "مبدل IP",
    LABEL_TITLE_LINK_FOOTER_FIRST_8_EN: "(HEADEND)هدند",
    LABEL_TITLE_LINK_FOOTER_SECOND_1_EN: "روتر",
    LABEL_VERIFY_CODE:"کد اعتبار سنجی",
    LABEL_TITLE_LINK_FOOTER_SECOND_2_EN: "کنترل پنل",
    LABEL_TITLE_LINK_FOOTER_THREE_1_EN: "پردازنده چند تصویری",
    LABEL_TITLE_LINK_FOOTER_THREE_2_EN: " مانیتورینگ سیگنال TS",
    LABEL_TITLE_LINK_FOOTER_FOURTH_1_EN: "پنل کاربری نرم افزار",
    LABEL_TITLE_LINK_FOOTER_FOURTH_2_EN: "پنل کاربری سخت افزار",
    LABEL_TITLE_LINK_FOOTER_FOURTH_3_EN: "دستگاه رابط ارتباط با استودیوو دوربین",
    LABEL_TITLE_LINK_FOOTER_FOURTH_4_EN: "سیستم جامع مدیریت و تولید محتوای زنده",
    LABEL_PHONE_ONE_EN: "+98 21 41021000 (30 خط)",
    LABEL_PHONE_TWO_EN: "+98 21 41021100",
    LABEL_ADDRESS_EN: "ایرانشهر جنوبی، ساختمان 47",
    LABEL_ZIP_CODE_EN: "کد پستی : 1581633953",
    LABEL_EMAIL_EN: "info@samimgroup.com",
    LABEL_COPY_RIGHT_FOOTER: "Copyright © SAMIM Group 1998-2020",
    LABLE_ABOUT_TEXT_FOOTER_EN: "گروه مهندسی صمیم به عنوان یکی از پیشگامان فناوری رسانه و تولید کننده تجهیزات پیشرفته در کلاس جهانی شناخته می‌شود. نوآوری مداوم از طریق تحقیق و توسعه، ارتقا کیفی محصولات و طراحی و تولید راهکارهای اختصاصی برای مشتریان، خط مشی این شرکت بوده و گروه صمیم ارائه محصولات مرغوب با استانداردهای بین المللی را تضمین می‌کند.",
    LABEL_HEADER_LOGIN_EN: "ورود",
    LABEL_HEADER_CHANGE_LANGUAGE: "English",
    LABEL_HEADER_ABOUT_US_EN: "SAMIM at glance",
    LABEL_HEADER_ABOUT_US_PERMISSION_EN: "Permissions",
    LABEL_HEADER_ABOUT_US_CUSTOMERS_EN: "Customers",
    LABEL_HEADER_ABOUT_US_HONORS_EN: "Honors",
    LABEL_MAIN_TITLE_HOME_PAGE_NEW_PRODUCTS: "محصولات",
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS: "پروژه ها",
    LABEL_MAIN_TITLE_HOME_PAGE_OUR_CUSTOMER: "مشتریان",
    LABEL_MAIN_TITLE_HOME_PAGE_OUR_SOLUTIONS: "راهکار ها",
    LABEL_MAIN_TITLE_HOME_PAGE_SAMIM_BLOG: "صمیم بلاگ",
    LABEL_HOME_PAGE_NEW_PRODUCTS_MODULAR_PRODUCTS: "محصولات ماژولار",
    LABEL_HOME_NEW_PRODUCTS_STREAMER: "هدند و RF",
    LABEL_HOME_PAGE_NEW_PRODUCTS_PROCESSOR_SIGNAL: "پردازش سیگنال",
    LABEL_HOME_PAGE_NEW_PRODUCTS_CREATE_LIVE: "تولید و پخش زنده",
    LABEL_HOME_PAGE_NEW_PRODUCTS_ROUTERTERS_AND_CONTROL_PANELS: "روتر و کنترل پنل",
    LABEL_HOME_PAGE_NEW_PRODUCTS_MUlTIVIEWER: "مالتی ویوئر",
    LABEL_HOME_PAGE_NEW_PRODUCTS_SMART_CAMERA: "دوربین هوشمند",
    LABEL_HOME_PAGE_NEW_PRODUCTS_IP_INTERCOM: "اینتر کام",
    LABEL_HOME_PAGE_BUTTON_ALL_PRODUCT_E: "همه محصولات",
    LABEL_HOME_PAGE_BUTTON_ALL_PROJECTS_E: "همه پروژه ها",
    LABEL_HOME_PAGE_BUTTON_ALL_CUSTOMER_E: "همه مشتریان",
    LABEL_HOME_PAGE_BUTTON_ALL_POSTS_E: "همه مطالب",
    LABEL_HOME_PAGE_BUTTON_ALL_SOLUTION_E: "همه راهکار ها",
    LABEL_MAIN_HOME_PAGE_TOP_PROJECT_FIRST_LEFT_E: "سامانه هوشمند محاسبه زمان ",
    LABEL_MAIN_HOME_PAGE_TOP_PROJECT_FIRST_RIGHT_E: "سیستم مانیتورینگ دیداری - شنیداری",
    LABEL_MAIN_HOME_PAGE_MORE_BUTTON_BLOG: "اطلاعات بیشتر",
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_SCALABILITY: 'Scalability',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_RELIABILITY: 'Reliability',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_FLEXIBILITY: 'Flexibility',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_VARIFOCAL_LENS: 'Varifocal Lens',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_VARIFOCAL_LENS_FIRST_SECTION: 'Varifocal',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_VARIFOCAL_LENS_TWO_SECTION: 'Lens',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_REAL_TIME: 'Real Time',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_MULTI_PROCESSOR: 'Multi Image Processor',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_MULTI_PROCESSOR_ONE_SECTION: 'Multi Image',
    LABEL_MAIN_TITLE_HOME_PAGE_TOP_PROJECTS_MULTI_PROCESSOR_TWO_SECTION: 'Processor',
    LABEL_MAIN_TITLE_HOME_PAGE_SLIDER_SMALL_1: "مجموعه ای کار آمد از پیشرفته ترین تکنولوژی های پردازش صدا و تصویر",
    LABEL_MAIN_TITLE_HOME_PAGE_SLIDER_SMALL_2: "نمایش همزمان چهل ورودی روی یک مانیتور",
    LABEL_MAIN_TITLE_HOME_PAGE_SLIDER_SMALL_3: "سیستم یکپارچه ارتباط صوتی در بستر شبکه",
    LABEL_SMALL_SLIDER_MORE_INFORMATION_E: "اطلاعات بیشتر",
    LABEL_ABOUT_US_PAGE_MAIN_TITLE: "شرکت مهندسی تحقیق و توسعه ارتباطات صمیم",
    LABEL_ABOUT_US_PAGE_SUB_TITLE: "فناوری رسانه و ارتباطات",
    LABEL_ACHIEVEMENTS_PAGE_MAIN_TITLE: "افتخارات",
    LABEL_ACHIEVEMENTS_PAGE_SUB_TITLE: "گروه مهندسی صمیم",
    LABEL_PERMISSIONS_PAGE_MAIN_TITLE: "مجوزها",
    LABEL_PERMISSIONS_PAGE_SUB_TITLE: "گروه مهندسی صمیم",
    LABEL_CUSTOMERS_PAGE_MAIN_TITLE: "مشتریان",
    LABEL_FORM_JOB_PAGE_MAIN_TITLE: "فرم تقاضای کار",
    LABEL_FORM_JOB_PAGE_SUB_TITLE: "اطلاعات شخصی",
    LABEL_CAREERS_PAGE_MAIN_TITLE: "به تیم رویایی بپیوندید",
    LABEL_CAREERS_PAGE_SUB_TITLE: "ما همیشه برای پیوستن به تیم خود در جستجوی استعدادهای لیست A هستیم.",
    LABEL_CUSTOMERS_PAGE_SUB_TITLE: "گروه مهندسی صمیم",
    LABEL_TAGES: 'تگ ها',
    LABEL_TEXT_BUTTON_DATASHEET: "DataSheet",
    LABEL_TEXT_BUTTON_USER_MANUAL: "User Manual",
    LABEL_TEXT_LOGIN_PAGE: "برای دسترسی به موارد زیر وارد شوید :",
    LABEL_TEXT_LOGIN_PAGE_LI_1: "دانلود مستندات و داکیومنت ها ",
    LABEL_TEXT_LOGIN_PAGE_LI_2: "دانلود نرم افزار ها",
    LABEL_TEXT_LOGIN_PAGE_LI_3: " نرم افزار ها",
    LABEL_TEXT_LOGIN_PAGE_LI_4: "امکانات بیشتر",
    LABEL_TEXT_LOGIN_USERNAME_PLACEHOLDER: "name@samim.net",
    LABEL_TEXT_LOGIN_PASS_PLACEHOLDER: "password",
    LABEL_TEXT_LOGIN_USERNAME_TITLE: "نام کاربری",
    LABEL_TEXT_LOGIN_PASSWORD_TITLE: "کلمه عبور",
    LABEL_TEXT_FORGET_PASSWORD_TITLE: "کلمه عبور خود را فراموش کرده ام",
    LABEL_RELATED_ITEMS: "محصولات مرتبط",
    LABEL_BLOG_TITLE_LINK: "آخرین مطالب  توییتر",
    LABEL_BLOG_TITLE_INSTAGRAM: "آخرین مطالب لینکدین",
    LABEL_BLOG_TITLE_TAGS: "برچسب ها",
    LABEL_BUTTON_APPLY: "در خواست",
    LABEL_FORM_FIRST_NAME: "نام",
    LABEL_FORM_LAST_NAME: "نام خانوادگی",
    LABEL_FORM_NATIONAL: "ملیت",
    LABEL_FORM_GENDER: "جنسیت",
    LABEL_FORM_BIRTH_DAY: "تاریخ تولد",
    LABEL_FORM_MARITAL_STATUS: "وضعیت تاهل",
    LABEL_FORM_MILITARY_SERVICE: "وضعیت خدمت سربازی",
    LABEL_FORM_EXEMPTION_COMPLETION_DATE: "تاریخ تکمیل معافیت",
    LABEL_FORM_REMARKS_OF_CONSCRIPTION_OFFICE: "اظهارات دفتر سربازی",
    LABEL_FORM_PHONE_NUMBER: "شماره تلفن ",
    LABEL_FORM_MOBILE_NUMBER: "شماره تلفن همراه",
    LABEL_FORM_EMAIL: "آدرس ایمیل",
    LABEL_FORM_ADDRESS: "آدرس",
    LABEL_FORM_CAREER_FUTURE: "آینده شغلی مطلوب",
    LABEL_FORM_NUMBER_OF_CHILD: "تعداد فرزندان",
    LABEL_CONTACT_US_PAGE_MAIN_TITLE: "تماس با ما",
    LABEL_CONTACT_US_PAGE_SUB_TITLE: "درباره ی هرآنچه که مرتبط به شرکت یا خدماتمان می باشد با ما تماس بگیرید...ما بهترین پاسخ را در کوتاه ترین زمان ممکن به شما می دهیم",
    LABEL_FORM_CONTACT_US_ADDRESS_TITLE: "آدرس :",
    LABEL_FORM_CONTACT_US_TELL_TITLE: "تلفن :",
    LABEL_FORM_CONTACT_US_ADDRESS: "ایرانشهر جنوبی، ساختمان 47",
    LABEL_FORM_CONTACT_US_TELL: "41021000 21 98+ (30 خط)",
    LABEL_FORM_CONTACT_US_TITLE_FAX: "فکس :",
    LABEL_FORM_CONTACT_US_FAX: "41021100 21 98+",
    LABEL_FORM_CONTACT_US_TITLE_MANAGEMENT: "مدیریت :",
    LABEL_FORM_CONTACT_US_MANAGEMENT: "director@samimgroup.com",
    LABEL_FORM_CONTACT_US_TITLE_SALE: "فروش :",
    LABEL_FORM_CONTACT_US_SALE: "sales@samimgroup.com",
    LABEL_FORM_CONTACT_US_TITLE_TS: "پشتیبانی فنی :",
    LABEL_FORM_CONTACT_US_TS: "ts@samimgroup.com",
    LABEL_SEND: 'ارسال',
    LABEL_CONTACT_US_MESSAGE: 'پیام شما',
    LABEL_CONTACT_US_NAME: 'نام شما:',
    LABEL_CONTACT_US_EMAIL: 'آدرس ایمیل',
    LABEL_CONTACT_US_PHONE_NUMBER: 'شماره تلفن (اختیاری)',
    LABEL_CONTACT_US_SOCIAL: 'شبکه های اجتماعی :',
    LABEL_SOLUTION_IMAM_PAGE_MAIN_TITLE: 'iMAM',
    LABEL_SOLUTION_IMAM_PAGE_SUB_TITLE: 'سامانه یکپارچه مدیریت محتوا',
    LABEL_ALL_PRODUCT: 'همه محصولات',
    LABEL_TEXT_BUTTON_DOWNLOAD_PDF: 'دانلود PDF',
    LABEL_TOP_PROJECTS_SYSTEM_MONITORING: 'سیستم مانیتورینگ دیداری-شنیداری',
    LABEL_TOP_PROJECTS_SMART_SYSTEM: 'سامانه هوشمند محاسبه زمان',
    LABEL_TOP_PROJECTS_BAZAR_MOHTAVA: 'بازار محتوا',
    LABEL_TOP_PROJECTS_HEAD_MONITORING: 'مانیتورینگ رئیس',
    LABEL_ERROR_NAME: "نام نمی تواند خالی باشد.",
    LABEL_ERROR_EMAIL: "آدرس ایمیل نمی تواند خالی باشد.",
    LABEL_ERROR_MOBILE: "موبایل نمی تواند خالی باشد.",
    LABEL_ERROR_MESSAGE: "پیام نمی تواند خالی باشد.",
    LABEL_MESSAGE_SUCCESS: "پیام شما با موفقیت ارسال شد.",
    LABEL_ERROR_LOGIN_PASSWORD: "کلمه عبور خود را به درست وارد نمایید",
    LABEL_ERROR_LOGIN_USERNAME: "آدرس ایمیل خود را وارد نمایید",
    LABEL_ERROR_LOGIN_INFORMATION: "اطلاعات را به صورت صحیح وارد نمایید",
    LABEL_ERROR_LOGIN_INFORMATION_CAPCHA: "کپچا را درست وارد نمایید",
    LABEL_SEARCH_PLACEHOLDER: "جستجو...",
    LABEL_TITLE_RESULT_SEARCH: "نتایج جستجو:",
    LABEL_TITLE_RESULT_SEARCH_IN_PRODUCTS: "نتایج جستجو در محصولات :",
    LABEL_TITLE_RESULT_SEARCH_IN_BLOG: "نتایج جستجو در بلاگ :",
    LABEL_TITLE_NOT_RESULT_SEARCH_IN_BLOG: "موردی یافت نشد.",
    LABEL_TITLE_NOT_FOUNT: "صفحه مورد نظر یافت نشد.",
    LABEL_TAG_TITLE: " | گروه صمیم",
    LABEL_INTRODUCTION: "گروه مهندسی صمیم",
    LABEL_ERROR_LOGIN_MOBILE:"شماره موبایل شما ثبت نشده است"

}
